### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by zlite4** [fabston/Discord-Airdrop-Bot#2]
I don't understand how the bot is funded to begin with. Is there a way to run this so it will generate an address rather than needing an outside address to make transfer to multiple users cheaper?

Can you make these changes?
Also is it possible the bot could issue nft's with any token from polygon network?

**Comment by fabston** [comment]
Hi there,

The bot does not communicate with the blockchain at all. It pretty much just collects addresses and then you’d have to use a different service to distribute the tokens.
